Repository micronaut-projects/static-website, pull requests merged in 2020-08, with the labels that each got.

#125 Webinar Serverless Micronaut on Google Cloud Platform
  posts/2020-08-03-serverless-micronaut-on-google-cloud-platform.md
Labels: blog

#138 build: update to gradle 6.6
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#130 publishing and reviewing local changes post
  posts/2020-08-14-contributing-to-micronaut-publishing-and-reviewing-local-changes.md
Labels: blog

#116 Changes to support page
  assets/images/iconCloudQuickStart.svg
  assets/images/iconMicronautLaunchpad.svg
  assets/images/iconMonolithToMicronaut.svg
  assets/images/iconNanoserviceQuickStart.svg
  assets/images/iconTrainingJumpstart.svg
  assets/stylesheets/screen.css
  pages/support.html
  posts/2020-07-31-introduction-to-microcronaut-at-merida-jug.md
Labels: type: improvement

#150 fix: don't suggest same blog post
  buildSrc/src/main/groovy/io/micronaut/gradle/BlogTask.groovy
  posts/2020-08-25-hands-on-lab-building-java-cloud-native-applications-with-micronaut-and-oci.md
Labels: type: bug

#149 blog: Post about Micronaut 2 Q&A session video
  posts/2020-08-28-micronaut-2-launching-the-technology-of-the-future.md
Labels: blog

#155 post: lambda post
  posts/2020-08-31-aws-lambda-runtime-custom.png
  posts/2020-08-31-aws-lambda-runtime-java11.png
  posts/2020-08-31-micronaut-2-aws-lambda.md
Labels: blog
